---
# NOT WORKING BECAUSE https://github.com/angristan/openvpn-install/blob/master/openvpn-install.sh#L1229
- hosts: openvpn
  gather_facts: no

  tasks:
    - include_role:
        name: ../openvpn-simple
      tags: [ all, uninstall, uninstall-debug, debug ]