---
- name: "Task details.."
  vars:
    msg: |
      Install simple OpenVPN based on
      {{ deploy.simple.script }}
  debug:
    msg: "{{ msg.split('\n') }}"
  tags: [ install-debug ]

- name: "Ensure '/tmp/openvpn-simple.sh' is absent"
  file:
    path: /tmp/openvpn-simple.sh
    state: absent
  tags: [ install ]

- name: "Download simple OpenVPN script.."
  get_url:
    url: "{{ deploy.simple.script }}"
    dest: /tmp/openvpn-simple.sh
  tags: [ install ]

- name: "Install simple OpenVPN server.."
  environment:
    AUTO_INSTALL: "{{ deploy.simple.envs.auto_install }}"
    APPROVE_INSTALL: "{{ deploy.simple.envs.approve_install }}"
    IPV6_SUPPORT: "{{ deploy.simple.envs.ipv6_support }}"
    PORT_CHOICE: "{{ deploy.simple.envs.port_choice }}"
    PROTOCOL_CHOICE: "{{ deploy.simple.envs.protocol_choice }}"
    DNS: "{{ deploy.simple.envs.dns }}"
    COMPRESSION_ENABLED: "{{ deploy.simple.envs.compression_enabled }}"
    CUSTOMIZE_ENC: "{{ deploy.simple.envs.customize_enc }}"
    CLIENT: "{{ deploy.simple.envs.client }}"
    PASS: "{{ deploy.simple.envs.pass }}"
  command: /bin/bash /tmp/openvpn-simple.sh
  register: installResult
  tags: [ install ]

- name: "Result: Install simple OpenVPN server.."
  debug:
    msg: "{{ installResult }}"
  tags: [ install-debug ]
  when: installResult is defined

- name: "Ensure '/tmp/openvpn-simple.sh' is absent.."
  file:
    path: /tmp/openvpn-simple.sh
    state: absent
  tags: [ install ]