---
- import_tasks: debug.yaml
  tags: [ debug ]

- import_tasks: install.yaml
  when: >
    deploy.enabled is defined and
    deploy.simple.enabled is defined and
    deploy.enabled|bool == true and
    deploy.simple.enabled|bool == true
  tags: [ install ]

- import_tasks: uninstall.yaml
  when: >
    deploy.enabled is defined and
    deploy.simple.enabled is defined and
    deploy.enabled|bool == true and
    deploy.simple.enabled|bool == true
  tags: [ uninstall ]