---
- name: "Task details.."
  vars:
    msg: |
      Uninstall simple OpenVPN based on
      {{ deploy.simple.script }}
  debug:
    msg: "{{ msg.split('\n') }}"
  tags: [ uninstall-debug ]

- name: "Ensure '/tmp/openvpn-simple.sh' is absent"
  file:
    path: /tmp/openvpn-simple.sh
    state: absent
  tags: [ uninstall ]

- name: "Download simple OpenVPN script.."
  get_url:
    url: "{{ deploy.simple.script }}"
    dest: /tmp/openvpn-simple.sh
  tags: [ uninstall ]

- name: "Uninstall simple OpenVPN server.."
  environment:
    MENU_OPTION: "3"
  command: /bin/bash /tmp/openvpn-simple.sh
  register: uninstallResult
  tags: [ uninstall ]

- name: "Result: Install simple OpenVPN server.."
  debug:
    msg: "{{ uninstallResult }}"
  tags: [ uninstall-debug ]
  when: uninstallResult is defined

- name: "Ensure '/tmp/openvpn-simple.sh' is absent.."
  file:
    path: /tmp/openvpn-simple.sh
    state: absent
  tags: [ uninstall ]